# Generated by Django 3.2.9 on 2023-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('Application', 'Application'), ('Bearer', 'Bearer')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='taiga_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
