# Generated by Django 3.2.9 on 2023-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_taiga_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='application_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('Application', 'Application'), ('Bearer', 'Bearer')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='taiga_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
