CHOISE_DOMAIN_OFFER = "Выберите домен сервера с тайгой, к которому нам надо обращаться"
CHOISE_STANDARD_TAIGA_DOMAIN = "Стандартный домен тайги (https://api.taiga.io/)"
CHOISE_NOT_STANDARD_TAIGA_DOMAIN = "Ввести свой домен(можете усточнить у своего администратора)"
INPUT_YOUR_DOMAIN = "Введите домен(адрес) по которому мы можем обращаться к вашей тайге"
STANDARD_AUTH_TYPE = "Стандартный по логину и паролю"
APPLICATION_AUTH_TYPE = "По токену приложения и логину с паролем"
CHOISE_AUTH_TYPE = "Выберите тип авторизации"
LINK_FOR_AUTH=""