# Generated by Django 3.2.9 on 2023-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_botuser_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='tg_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
